### ISSUE TITLE
There are yarp binaries

### ISSUE THREAD

**Issue by alecive** [iron76/beaglebone-black-yarp#2]
@iron76 don't know if it is useful for your task or not, but here https://github.com/alecive/yarpdroid there are some precompiled yarp libraries for `arm-v7` architectures. I compiled only `YARP_OS`, `YARP_sig` and `YARP_init` because they were useful for my purposes (i.e. the `yarpdroid` Android application), but I might upload even other libraries if needed.

**Comment by iron76** [comment]
Thanks for the information. I am currently compiling YARP every time I want to install it on a new board but binaries would be definitively useful. Thanks.
