### ISSUE TITLE
||| did not find ymanager.ini

### ISSUE THREAD

**Issue by kzts** [iron76/beaglebone-black-yarp#4]
I put following
`yarpmanager --application $BBB_YARP_DIR/beaglebone-black-yarp/conf/app.xml`

I got following messages.

```
||| did not find ymanager.ini
yarp: cannot read from ymanager.ini
||| did not find ymanager.ini
```

**Comment by iron76** [comment]
It is not an error. You can proceed. It is just missing a configuration file which is not needed.
